import { RegisterDefinition } from "../types.ts";

export const DEFAULT_SETTINGS = {
  kejaksaanName: "KEJAKSAAN NEGERI TABANAN",
  tempatDokumen: "Tabanan",
  tanggalDokumen: new Date().toISOString().split("T")[0],
  leftSignerTitle: "Mengetahui:\nKEPALA KEJAKSAAN NEGERI TABANAN",
  leftSignerName: "ZAINUR ARIFIN SYAH, S.H., M.H.",
  leftSignerPangkatNip: "Jaksa Utama Pratama / NIP. 19740512 199903 1 002",
  rightSignerTitle: "KEPALA SEKSI INTELIJEN",
  rightSignerName: "I GUSTI NGURAH ANOM SUKASIH, S.H.",
  rightSignerPangkatNip: "Jaksa Muda / NIP. 19820815 200712 1 001",
};

export const INITIAL_OFFICERS = [
  {
    nama: "I GUSTI NGURAH ANOM SUKASIH, S.H.",
    pangkat: "Jaksa Muda (III/d)",
    nip: "19820815 200712 1 001",
    jabatan: "Kepala Seksi Intelijen",
  },
  {
    nama: "I WAYAN GEDE PUTRA YASA, S.H., M.H.",
    pangkat: "Jaksa Pratama (III/c)",
    nip: "19880324 201012 1 003",
    jabatan: "Kasubsi Ideologi, Politik, Hankam dan Sosbudmas",
  },
  {
    nama: "NI KETUT RAI ARTINI, S.H.",
    pangkat: "Jaksa Pratama (III/c)",
    nip: "19900412 201212 2 002",
    jabatan: "Kasubsi Ekonomi, Keuangan & PPS",
  },
  {
    nama: "MADE ARDIKA KUSUMA, S.Kom.",
    pangkat: "Penata Muda Tk. I (III/b)",
    nip: "19930718 201712 1 004",
    jabatan: "Pranata Komputer / Petugas TI & Sandi",
  },
  {
    nama: "I PUTU AGUS ADNYANA, A.Md.",
    pangkat: "Pengatur Tk. I (II/d)",
    nip: "19960205 201901 1 002",
    jabatan: "Petugas Administrasi Intelijen / Arsiparis",
  },
];

export const SEKTOR_OPTIONS_BIDANG = {
  ideologi: [
    "Pengamanan Pancasila",
    "Kesatuan dan persatuan bangsa",
    "Gerakan separatis",
    "Penyelenggaraan pemerintahan",
    "Partai politik",
    "Pemilihan umum dan pemilihan kepala daerah",
    "Gerakan teroris dan radikal",
    "Pengamanan wilayah teritorial",
    "Kejahatan siber",
    "Cegah tangkal",
    "Pengawasan orang asing",
    "Pengamanan sumber daya organisasi Kejaksaan",
    "Pengamanan penanganan perkara",
  ],
  sosbud: [
    "Pengawasan Peredaran barang cetakan dalam negeri",
    "Pengawasan peredaran impor barang cetakan",
    "Pengawasan sistem perbukuan",
    "Pengawasan media komunikasi",
    "Pengawasan aliran kepercayaan dan keagamaan dalam masyarakat",
    "Pencegahan penyalahgunaan dan/atau penodaan agama",
    "Ketahanan budaya",
    "Pemberdayaan masyarakat desa",
    "Pengawasan organisasi masyarakat dan LSM",
    "Pencegahan konflik sosial",
    "Ketertiban dan ketentraman umum",
    "Pembinaan masyarakat taat hukum",
  ],
  ekkeu: [
    "Lembaga keuangan",
    "Keuangan negara",
    "Moneter",
    "Penelusuran aset",
    "Investasi/penanaman modal",
    "Perpajakan",
    "Kepabeanan",
    "Cukai",
    "Perdagangan",
    "Perindustrian",
    "Ketenagakerjaan",
    "Perkebunan",
    "Kehutanan",
    "Lingkungan hidup",
    "Perikanan",
    "Agraria/tata ruang",
  ],
  pps: [
    "Infrastruktur jalan",
    "Infrastruktur perkeretaapian",
    "Infrastruktur kebandarudaraan",
    "Infrastruktur telekomunikasi",
    "Infrastruktur kepelabuhanan",
    "Smelter",
    "Infrastruktur pengolahan air",
    "Tanggul & Bendungan",
    "Pertanian & Kelautan",
    "Ketenagalistrikan & Energi alternatif",
    "Minyak & gas bumi",
    "Ilmu pengetahuan dan teknologi",
    "Perumahan & Pariwisata",
    "Kawasan industri prioritas/KEK",
    "Pos lintas batas negara & sarana penunjang",
    "Sektor strategis lainnya",
  ],
  ti_intel: [
    "Produksi intelijen",
    "Pemantauan & Intelijen Sinyal",
    "Intelijen siber",
    "Klandestine & Digital forensik",
    "Transmisi berita sandi",
    "Kontra penginderaan",
    "Audit & pengujian sistem keamanan informasi",
    "Pengamanan sinyal",
    "Pengembangan SDM & sandi intelijen",
    "Pengembangan teknologi & aplikasi prosedur",
  ],
};

export const REGISTER_DEFINITIONS: RegisterDefinition[] = [
  {
    code: "R.IN.1",
    number: 1,
    title: "REGISTER SURAT MASUK BIASA/RAHASIA",
    category: "Surat & Berita",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      {
        key: "waktu_penerimaan",
        label: "WAKTU PENERIMAAN SURAT",
        colNumber: "2-3",
        type: "text",
        subColumns: [
          { key: "tgl_terima", label: "TGL", colNumber: 2, type: "date" },
          { key: "jam_terima", label: "JAM", colNumber: 3, type: "time" },
        ],
      },
      {
        key: "surat_masuk",
        label: "SURAT MASUK",
        colNumber: "4-5",
        type: "text",
        subColumns: [
          { key: "nomor_surat", label: "NOMOR", colNumber: 4, type: "text" },
          { key: "tgl_surat", label: "TGL", colNumber: 5, type: "date" },
        ],
      },
      { key: "asal_surat", label: "ASAL SURAT", colNumber: 6, type: "text" },
      { key: "perihal", label: "PERIHAL", colNumber: 7, type: "textarea" },
      {
        key: "disposisi",
        label: "DISPOSISI",
        colNumber: "8-9",
        type: "text",
        subColumns: [
          { key: "tgl_isi_disposisi", label: "TGL/ISI", colNumber: 8, type: "textarea" },
          { key: "tindak_lanjut", label: "TINDAK LANJUT", colNumber: 9, type: "text" },
        ],
      },
      { key: "keterangan", label: "KET", colNumber: 10, type: "text" },
    ],
  },
  {
    code: "R.IN.2",
    number: 2,
    title: "REGISTER SURAT KELUAR BIASA/RAHASIA",
    category: "Surat & Berita",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO.", colNumber: 1, type: "number", widthPercent: 6 },
      { key: "tgl_no_surat", label: "TGL DAN NO SURAT", colNumber: 2, type: "text" },
      { key: "kepada", label: "KEPADA", colNumber: 3, type: "text" },
      { key: "perihal", label: "PERIHAL", colNumber: 4, type: "textarea" },
      { key: "lampiran", label: "LAMPIRAN", colNumber: 5, type: "text" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.3",
    number: 3,
    title: "REGISTER KERJA INTELIJEN",
    subtitle: "IDEOLOGI, POLITIK, PERTAHANAN DAN KEAMANAN / SOSIAL BUDAYA DAN KEMASYARAKATAN / EKONOMI DAN KEUANGAN / PENGAMANAN PEMBANGUNAN STRATEGIS / TEKNOLOGI INFORMASI DAN PRODUKSI INTELIJEN",
    category: "Kerja & Produk",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan. **) Dibuat sesuai masing-masing bidang.",
    bidangOptions: [
      "Ideologi, Politik, Pertahanan dan Keamanan",
      "Sosial, Budaya, dan Kemasyarakatan",
      "Ekonomi, dan Keuangan",
      "Pengamanan Pembangunan Strategis",
      "Teknologi Informasi, dan Produksi Intelijen",
    ],
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "waktu_diterima", label: "WAKTU DITERIMA", colNumber: 2, type: "datetime" },
      { key: "sumber_bapul", label: "SUMBER/BAPUL", colNumber: 3, type: "text" },
      { key: "nilai_data", label: "NILAI DATA/INFORMASI", colNumber: 4, type: "select", options: ["A1", "A2", "A3", "B1", "B2", "B3", "C1", "C2", "C3", "D4", "E5", "F6"] },
      { key: "uraian_peristiwa", label: "URAIAN PERISTIWA/MASALAH", colNumber: 5, type: "textarea" },
      { key: "catatan", label: "CATATAN", colNumber: 6, type: "text" },
      { key: "disposisi_tindakan", label: "DISPOSISI/TINDAKAN", colNumber: 7, type: "text" },
      { key: "tindak_lanjut", label: "TINDAK LANJUT", colNumber: 8, type: "text" },
      { key: "keterangan", label: "KET", colNumber: 9, type: "text" },
    ],
  },
  {
    code: "R.IN.4",
    number: 4,
    title: "REGISTER EKSPEDISI SURAT BIASA/RAHASIA",
    category: "Surat & Berita",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO.", colNumber: 1, type: "number", widthPercent: 6 },
      { key: "no_tgl_surat", label: "NO DAN TGL SURAT", colNumber: 2, type: "text" },
      { key: "kepada", label: "KEPADA", colNumber: 3, type: "text" },
      { key: "perihal", label: "PERIHAL", colNumber: 4, type: "textarea" },
      { key: "lampiran", label: "LAMPIRAN", colNumber: 5, type: "text" },
      {
        key: "tanda_terima",
        label: "TANDA TERIMA",
        colNumber: "6-7",
        type: "text",
        subColumns: [
          { key: "waktu_terima", label: "WAKTU", colNumber: 6, type: "datetime" },
          { key: "nama_paraf", label: "NAMA DAN PARAF", colNumber: 7, type: "text" },
        ],
      },
      { key: "keterangan", label: "KETERANGAN", colNumber: 8, type: "text" },
    ],
  },
  {
    code: "R.IN.5",
    number: 5,
    title: "REGISTER PRODUK INTELIJEN",
    category: "Kerja & Produk",
    orientation: "landscape",
    hasRekapitulasi: true,
    rekapitulasiFields: [
      { label: "Jumlah Telaahan Intelijen", key: "rekap_telaahan" },
      { label: "Jumlah Laporan Informasi Harian (LIH)", key: "rekap_lih" },
      { label: "Jumlah Laporan Informasi Khusus (LIK)", key: "rekap_lik" },
      { label: "Jumlah Laporan Hasil Operasi (LHO)", key: "rekap_lho" },
    ],
    notes: "*) Kejaksaan ditulis hanya di sampul depan. **) Diisi nama struktural sesuai pengisian kolom 4.",
    columns: [
      { key: "no", label: "NO.", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "jenis_produk", label: "JENIS PRODUK INTELIJEN", colNumber: 2, type: "select", options: ["Telaahan Intelijen", "Laporan Informasi Harian (LIH)", "Laporan Informasi Khusus (LIK)", "Laporan Hasil Operasi (LHO)", "Laporan Atensi", "Petunjuk Intelijen"] },
      { key: "nomor_tgl_produk", label: "NOMOR DAN TANGGAL PRODUK INTELIJEN", colNumber: 3, type: "text" },
      { key: "subdit_seksi", label: "SUBDIT/SEKSI/SUBSEKSI", colNumber: 4, type: "text" },
      { key: "perihal", label: "PERIHAL", colNumber: 5, type: "textarea" },
      { key: "disposisi_pimpinan", label: "DISPOSISI PIMPINAN", colNumber: 6, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 7, type: "text" },
    ],
  },
  {
    code: "R.IN.6",
    number: 6,
    title: "REGISTER ARSIP",
    category: "Surat & Berita",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 6 },
      { key: "waktu_terima", label: "WAKTU TERIMA", colNumber: 2, type: "datetime" },
      { key: "diterima_dari", label: "DITERIMA DARI", colNumber: 3, type: "text" },
      { key: "no_tgl_surat", label: "NO. & TGL SURAT", colNumber: 4, type: "text" },
      { key: "perihal", label: "PERIHAL", colNumber: 5, type: "textarea" },
      { key: "lampiran", label: "LAMPIRAN", colNumber: 6, type: "text" },
      { key: "kode_penyimpanan", label: "KODE PENYIMPANAN", colNumber: 7, type: "text" },
      { key: "keterangan", label: "KET", colNumber: 8, type: "text" },
    ],
  },
  {
    code: "R.IN.7",
    number: 7,
    title: "REGISTER KEGIATAN BIDANG IDEOLOGI, POLITIK, PERTAHANAN DAN KEAMANAN, CEGAH TANGKAL DAN PENGAWASAN ORANG ASING, PENGAMANAN SUMBER DAYA ORGANISASI KEJAKSAAN DAN PENGAMANAN PENANGANAN PERKARA",
    category: "Kegiatan Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "sektor", label: "SEKTOR", colNumber: 2, type: "select", options: SEKTOR_OPTIONS_BIDANG.ideologi },
      {
        key: "surat_perintah",
        label: "SURAT PERINTAH/DISPOSISI",
        colNumber: "3-4",
        type: "text",
        subColumns: [
          { key: "no_tgl_peruntukan", label: "NOMOR, TANGGAL DAN PERUNTUKAN SURAT PERINTAH/DISPOSISI", colNumber: 3, type: "textarea" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 4, type: "officer_multi" },
        ],
      },
      { key: "hasil_pelaksanaan", label: "HASIL PELAKSANAAN KEGIATAN", colNumber: 5, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.8",
    number: 8,
    title: "REGISTER KEGIATAN BIDANG SOSIAL BUDAYA DAN KEMASYARAKATAN",
    category: "Kegiatan Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "sektor", label: "SEKTOR", colNumber: 2, type: "select", options: SEKTOR_OPTIONS_BIDANG.sosbud },
      {
        key: "surat_perintah",
        label: "SURAT PERINTAH/DISPOSISI",
        colNumber: "3-4",
        type: "text",
        subColumns: [
          { key: "no_tgl_peruntukan", label: "NOMOR, TANGGAL DAN PERUNTUKAN SURAT PERINTAH/DISPOSISI", colNumber: 3, type: "textarea" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 4, type: "officer_multi" },
        ],
      },
      { key: "hasil_pelaksanaan", label: "HASIL PELAKSANAAN KEGIATAN", colNumber: 5, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.9",
    number: 9,
    title: "REGISTER KEGIATAN BIDANG EKONOMI DAN KEUANGAN",
    category: "Kegiatan Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "sektor", label: "SEKTOR", colNumber: 2, type: "select", options: SEKTOR_OPTIONS_BIDANG.ekkeu },
      {
        key: "surat_perintah",
        label: "SURAT PERINTAH/DISPOSISI",
        colNumber: "3-4",
        type: "text",
        subColumns: [
          { key: "no_tgl_perihal", label: "NOMOR, TANGGAL DAN PERIHAL SURAT PERINTAH/DISPOSISI", colNumber: 3, type: "textarea" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 4, type: "officer_multi" },
        ],
      },
      { key: "hasil_pelaksanaan", label: "HASIL PELAKSANAAN KEGIATAN", colNumber: 5, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.10",
    number: 10,
    title: "REGISTER KEGIATAN BIDANG PENGAMANAN PEMBANGUNAN STRATEGIS",
    category: "Kegiatan Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 3 },
      { key: "sektor_kegiatan_dana", label: "SEKTOR, NAMA KEGIATAN & SUMBER DANA", colNumber: 2, type: "textarea" },
      { key: "kldi", label: "K/L/D/I", colNumber: 3, type: "text" },
      { key: "pagu_anggaran", label: "PAGU ANGGARAN", colNumber: 4, type: "text" },
      { key: "no_tgl_permohonan", label: "NO & TANGGAL SURAT PERMOHONAN", colNumber: 5, type: "text" },
      {
        key: "pemaparan_pemohon",
        label: "PEMAPARAN PEMOHON",
        colNumber: "6-7",
        type: "text",
        subColumns: [
          { key: "pemaparan_tempat", label: "TEMPAT", colNumber: 6, type: "text" },
          { key: "pemaparan_tanggal", label: "TANGGAL", colNumber: 7, type: "date" },
        ],
      },
      { key: "telaahan_intelijen", label: "TELAHAAN INTELIJEN", colNumber: 8, type: "text" },
      {
        key: "tindak_lanjut_permohonan",
        label: "TINDAK LANJUT PERMOHONAN",
        colNumber: "9-10",
        type: "text",
        subColumns: [
          { key: "status_diterima", label: "DITERIMA", colNumber: 9, type: "text" },
          { key: "status_ditolak", label: "DITOLAK", colNumber: 10, type: "text" },
        ],
      },
      {
        key: "sp_walpam",
        label: "SURAT PERINTAH WALPAM",
        colNumber: "11-12",
        type: "text",
        subColumns: [
          { key: "sp_walpam_no_tgl", label: "NOMOR/TANGGAL", colNumber: 11, type: "text" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS", colNumber: 12, type: "officer_multi" },
        ],
      },
      { key: "nilai_kontrak", label: "NILAI KONTRAK", colNumber: 13, type: "text" },
      { key: "efisiensi_anggaran", label: "EFISIENSI ANGGARAN", colNumber: 14, type: "text" },
      {
        key: "hasil_pengawalan",
        label: "HASIL PELAKSANAAN PENGAWALAN DAN PENGAMANAN",
        colNumber: "15-16",
        type: "text",
        subColumns: [
          { key: "proyek_selesai", label: "PROYEK SELESAI", colNumber: 15, type: "text" },
          { key: "penghentian", label: "PENGHENTIAN", colNumber: 16, type: "text" },
        ],
      },
      { key: "no_tgl_kertas_kerja", label: "NO & TANGGAL KERTAS KERJA", colNumber: 17, type: "text" },
      { key: "keterangan", label: "KET", colNumber: 18, type: "text" },
    ],
  },
  {
    code: "R.IN.11",
    number: 11,
    title: "REGISTER KEGIATAN BIDANG TEKNOLOGI INFORMASI DAN PRODUKSI INTELIJEN",
    category: "Kegiatan Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "sektor", label: "SEKTOR", colNumber: 2, type: "select", options: SEKTOR_OPTIONS_BIDANG.ti_intel },
      {
        key: "surat_perintah",
        label: "SURAT PERINTAH/DISPOSISI",
        colNumber: "3-4",
        type: "text",
        subColumns: [
          { key: "no_tgl_perihal", label: "NOMOR, TANGGAL DAN PERIHAL SURAT PERINTAH/DISPOSISI", colNumber: 3, type: "textarea" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 4, type: "officer_multi" },
        ],
      },
      { key: "hasil_pelaksanaan", label: "HASIL PELAKSANAAN KEGIATAN", colNumber: 5, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.12",
    number: 12,
    title: "REGISTER OPERASI INTELIJEN BIDANG IDEOLOGI, POLITIK, PERTAHANAN DAN KEAMANAN, CEGAH TANGKAL DAN PENGAWASAN ORANG ASING, PENGAMANAN SUMBER DAYA ORGANISASI KEJAKSAAN DAN PENGAMANAN PENANGANAN PERKARA",
    category: "Operasi Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "sektor", label: "SEKTOR", colNumber: 2, type: "select", options: SEKTOR_OPTIONS_BIDANG.ideologi },
      {
        key: "surat_perintah",
        label: "SURAT PERINTAH/DISPOSISI",
        colNumber: "3-4",
        type: "text",
        subColumns: [
          { key: "no_tgl_perihal", label: "NOMOR, TANGGAL DAN PERIHAL SURAT PERINTAH/DISPOSISI", colNumber: 3, type: "textarea" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 4, type: "officer_multi" },
        ],
      },
      { key: "hasil_pelaksanaan", label: "HASIL PELAKSANAAN KEGIATAN", colNumber: 5, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.13",
    number: 13,
    title: "REGISTER OPERASI INTELIJEN BIDANG SOSIAL BUDAYA DAN KEMASYARAKATAN",
    category: "Operasi Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "sektor", label: "SEKTOR", colNumber: 2, type: "select", options: SEKTOR_OPTIONS_BIDANG.sosbud },
      {
        key: "surat_perintah",
        label: "SURAT PERINTAH",
        colNumber: "3-4",
        type: "text",
        subColumns: [
          { key: "no_tgl_perihal", label: "NOMOR, TANGGAL DAN PERIHAL SURAT PERINTAH", colNumber: 3, type: "textarea" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 4, type: "officer_multi" },
        ],
      },
      { key: "hasil_pelaksanaan", label: "HASIL PELAKSANAAN OPERASI", colNumber: 5, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.14",
    number: 14,
    title: "REGISTER OPERASI INTELIJEN BIDANG EKONOMI DAN KEUANGAN",
    category: "Operasi Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "sektor", label: "SEKTOR", colNumber: 2, type: "select", options: SEKTOR_OPTIONS_BIDANG.ekkeu },
      {
        key: "surat_perintah",
        label: "SURAT PERINTAH",
        colNumber: "3-4",
        type: "text",
        subColumns: [
          { key: "no_tgl_perihal", label: "NOMOR, TANGGAL DAN PERIHAL SURAT PERINTAH", colNumber: 3, type: "textarea" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 4, type: "officer_multi" },
        ],
      },
      { key: "hasil_pelaksanaan", label: "HASIL PELAKSANAAN OPERASI", colNumber: 5, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.15",
    number: 15,
    title: "REGISTER OPERASI INTELIJEN BIDANG PENGAMANAN PEMBANGUNAN STRATEGIS",
    category: "Operasi Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "sektor", label: "SEKTOR", colNumber: 2, type: "select", options: SEKTOR_OPTIONS_BIDANG.pps },
      {
        key: "surat_perintah",
        label: "SURAT PERINTAH",
        colNumber: "3-4",
        type: "text",
        subColumns: [
          { key: "no_tgl_perihal", label: "NOMOR, TANGGAL DAN PERIHAL SURAT PERINTAH", colNumber: 3, type: "textarea" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 4, type: "officer_multi" },
        ],
      },
      { key: "hasil_pelaksanaan", label: "HASIL PELAKSANAAN OPERASI", colNumber: 5, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.16",
    number: 16,
    title: "REGISTER OPERASI INTELIJEN BIDANG TEKNOLOGI INFORMASI DAN PRODUKSI INTELIJEN",
    category: "Operasi Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "sektor", label: "SEKTOR", colNumber: 2, type: "select", options: SEKTOR_OPTIONS_BIDANG.ti_intel },
      {
        key: "surat_perintah",
        label: "SURAT PERINTAH",
        colNumber: "3-4",
        type: "text",
        subColumns: [
          { key: "no_tgl_perihal", label: "NOMOR, TANGGAL DAN PERIHAL SURAT PERINTAH", colNumber: 3, type: "textarea" },
          { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 4, type: "officer_multi" },
        ],
      },
      { key: "hasil_pelaksanaan", label: "HASIL PELAKSANAAN OPERASI", colNumber: 5, type: "textarea" },
      { key: "keterangan", label: "KETERANGAN", colNumber: 6, type: "text" },
    ],
  },
  {
    code: "R.IN.17",
    number: 17,
    title: "REGISTER BERITA MASUK BIASA/RAHASIA",
    subtitle: "Kamar Sandi",
    category: "Surat & Berita",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "tanggal", label: "TANGGAL", colNumber: 2, type: "date" },
      { key: "no_tgl_berita", label: "NO & TGL BERITA", colNumber: 3, type: "text" },
      { key: "dari", label: "DARI", colNumber: 4, type: "text" },
      { key: "kepada", label: "KEPADA", colNumber: 5, type: "text" },
      { key: "perihal", label: "PERIHAL", colNumber: 6, type: "textarea" },
      { key: "tgl_jam_diterima", label: "TGL/JAM DITERIMA", colNumber: 7, type: "datetime" },
      { key: "jumlah_halaman", label: "JUMLAH HALAMAN", colNumber: 8, type: "text" },
      { key: "nama_petugas_ids", label: "NAMA PETUGAS", colNumber: 9, type: "officer_multi" },
      { key: "keterangan", label: "KET", colNumber: 10, type: "text" },
    ],
  },
  {
    code: "R.IN.18",
    number: 18,
    title: "REGISTER BERITA KELUAR BIASA/RAHASIA",
    subtitle: "Kamar Sandi",
    category: "Surat & Berita",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "tanggal", label: "TANGGAL", colNumber: 2, type: "date" },
      { key: "nomor_tgl_berita", label: "NOMOR & TGL BERITA", colNumber: 3, type: "text" },
      { key: "dari", label: "DARI", colNumber: 4, type: "text" },
      { key: "kepada", label: "KEPADA", colNumber: 5, type: "text" },
      { key: "perihal", label: "PERIHAL", colNumber: 6, type: "textarea" },
      { key: "tgl_jam_dikirim", label: "TANGGAL DAN JAM DIKIRIM", colNumber: 7, type: "datetime" },
      { key: "jumlah_halaman", label: "JUMLAH HALAMAN", colNumber: 8, type: "text" },
      { key: "nama_petugas_ids", label: "NAMA PETUGAS", colNumber: 9, type: "officer_multi" },
      { key: "keterangan", label: "KET", colNumber: 10, type: "text" },
    ],
  },
  {
    code: "R.IN.19",
    number: 19,
    title: "REGISTER TELAAHAN INTELIJEN",
    category: "Kerja & Produk",
    orientation: "landscape",
    hasRekapitulasi: true,
    rekapitulasiFields: [
      { label: "Jumlah Telaahan Intelijen yang masuk", key: "telaahan_masuk", suffix: "Telaahan" },
      { label: "Jumlah Telaahan Intelijen yang ditindaklanjuti", key: "telaahan_tindaklanjut", suffix: "Telaahan" },
      { label: "Jumlah Telaahan Intelijen yang tidak ditindaklanjuti", key: "telaahan_tidaktindak", suffix: "Telaahan" },
    ],
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO.", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "tgl_no_telaahan", label: "TGL DAN NO. TELAAHAN INTELIJEN", colNumber: 2, type: "text" },
      { key: "pembuat", label: "PEMBUAT", colNumber: 3, type: "text" },
      { key: "perihal", label: "PERIHAL", colNumber: 4, type: "textarea" },
      { key: "lampiran", label: "LAMPIRAN", colNumber: 5, type: "text" },
      { key: "tindak_lanjut", label: "TINDAK LANJUT", colNumber: 6, type: "textarea" },
      { key: "keterangan", label: "KET", colNumber: 7, type: "text" },
    ],
  },
  {
    code: "R.IN.20",
    number: 20,
    title: "REGISTER EKSPEDISI BERITA BIASA/RAHASIA",
    subtitle: "Kamar Sandi",
    category: "Surat & Berita",
    orientation: "portrait",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 8 },
      { key: "no_berita", label: "NO. BERITA", colNumber: 2, type: "text" },
      { key: "kepada", label: "KEPADA", colNumber: 3, type: "text" },
      { key: "nama_ttd_penerima", label: "NAMA & TTD PENERIMA", colNumber: 4, type: "text" },
      { key: "keterangan", label: "KET", colNumber: 5, type: "text" },
    ],
  },
  {
    code: "R.IN.21",
    number: 21,
    title: "REGISTER TAMU POS PELAYANAN HUKUM (PPH) DAN PENERIMAAN PENGADUAN MASYARAKAT (PPM)",
    category: "Layanan & Penyuluhan",
    orientation: "landscape",
    hasRekapitulasi: true,
    rekapitulasiFields: [
      { label: "Pelapor tamu perorangan", key: "pelapor_perorangan", suffix: "orang" },
      { label: "Pelapor dari organisasi", key: "pelapor_organisasi", suffix: "orang" },
      { label: "Jumlah Pelapor", key: "pelapor_total", suffix: "orang" },
    ],
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO. URUT", colNumber: 1, type: "number", widthPercent: 4 },
      { key: "nama_petugas_penerima", label: "NAMA PETUGAS PENERIMA LAPORAN", colNumber: 2, type: "officer_single" },
      { key: "waktu_lapor", label: "WAKTU (HARI/TANGGAL/JAM)", colNumber: 3, type: "datetime" },
      { key: "identitas_pelapor", label: "IDENTITAS (Nama, TTL, Alamat, Jenis Kelamin, No HP, Email, Pekerjaan, No KTP/SIM/Passport)", colNumber: 4, type: "textarea" },
      { key: "nama_organisasi", label: "NAMA ORGANISASI", colNumber: 5, type: "text" },
      { key: "informasi_disampaikan", label: "INFORMASI YANG DISAMPAIKAN", colNumber: 6, type: "textarea" },
      { key: "surat_dokumen", label: "SURAT/DOKUMEN YANG DISAMPAIKAN", colNumber: 7, type: "text" },
      { key: "tanda_tangan", label: "TANDA TANGAN", colNumber: 8, type: "text" },
      { key: "keterangan", label: "KET", colNumber: 9, type: "text" },
    ],
  },
  {
    code: "R.IN.22",
    number: 22,
    title: "REGISTER PELAKSANAAN KEGIATAN PENERANGAN HUKUM / PENYULUHAN HUKUM",
    category: "Layanan & Penyuluhan",
    orientation: "landscape",
    notes: "*) Dibuat sesuai kegiatan penerangan hukum atau penyuluhan hukum.\n**) Disesuaikan dengan pejabat penyelenggara.\n***) Disesuaikan dengan atasan pejabat penyelenggara",
    columns: [
      { key: "no", label: "No", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "surat_perintah", label: "SURAT PERINTAH", colNumber: 2, type: "textarea" },
      { key: "sasaran_kegiatan", label: "SASARAN KEGIATAN", colNumber: 3, type: "text" },
      { key: "waktu", label: "WAKTU", colNumber: 4, type: "datetime" },
      { key: "tempat", label: "TEMPAT", colNumber: 5, type: "text" },
      { key: "materi", label: "MATERI", colNumber: 6, type: "textarea" },
      { key: "jumlah_peserta", label: "JUMLAH PESERTA", colNumber: 7, type: "text" },
      { key: "keterangan", label: "KET", colNumber: 8, type: "text" },
    ],
  },
  {
    code: "R.IN.23",
    number: 23,
    title: "REGISTER PENGAWASAN ORANG ASING / MEDIA & INFORMASI INTELIJEN",
    category: "Operasi Intelijen",
    orientation: "landscape",
    notes: "*) Kejaksaan ditulis hanya di sampul depan.",
    columns: [
      { key: "no", label: "NO", colNumber: 1, type: "number", widthPercent: 5 },
      { key: "surat_perintah", label: "SURAT PERINTAH / DASAR TUGAS", colNumber: 2, type: "textarea" },
      { key: "nama_petugas_ids", label: "NAMA PETUGAS PELAKSANA", colNumber: 3, type: "officer_multi" },
      { key: "sasaran_objek", label: "SASARAN / OBJEK PENGAWASAN", colNumber: 4, type: "textarea" },
      { key: "waktu_lokasi", label: "WAKTU & LOKASI PELAKSANAAN", colNumber: 5, type: "text" },
      { key: "hasil_pengamatan", label: "HASIL PENGAMATAN / TEMUAN", colNumber: 6, type: "textarea" },
      { key: "keterangan_saran", label: "KET & SARAN TINDAK", colNumber: 7, type: "text" },
    ],
  },
];
